### ISSUE TITLE
Allow setting a custom base url

### ISSUE THREAD

**Issue by NoamDev** [vollkorntomate/flutter-photon#1]
Being an open source product, you can run your own instance of photon.
In order to use it with this package you'd have to set a custom base url.

**Comment by NoamDev** [comment]
so it'd be something like that: `PhotonApi(baseUrl: 'http://example.com/api')`

**Comment by vollkorntomate** [comment]
Hi @NoamDev,
Thank you for pointing this out! I haven't thought about this at all.
I created version 0.2.0 which now supports custom URLs, just like you expect it. See commit a7d3be1.

If you need an insecure HTTP (not HTTPS) connection, make sure you set the `secure` parameter on the functions to `false`.

**Comment by NoamDev** [comment]
Have you run flutter test?
All tests are failing on my end.

**Comment by NoamDev** [comment]
It seems something in wrong with the URI construction.
"No host specifed in URI https:photon.komoot.io/api?q=munich"

**Comment by vollkorntomate** [comment]
I did run the tests, but then changed something which broke it again.
I just published the fixed version 0.2.1.
Sorry for the inconvenience!

**Comment by NoamDev** [comment]
Ok, great, consider setting up a CI. That way it would almost never happen.
