### ISSUE TITLE
Error when searching for oceans

### ISSUE THREAD

**Issue by hallabrin** [vollkorntomate/flutter-photon#8]
When searching for oceans (e.g. "atlantic ocean"), i found two problems:

- Coordinates are parsed as integers by the dart json parser and the LatLng package expects double
- Country and CountryIsoCode are null

Both issues are causing exceptions in the PhotonFeature.fromJson factory.
Also, is it really necessary to import the LatLng package only for the simple class definition?

**Comment by vollkorntomate** [comment]
Thank you for reporting and the PR! I merged your PR and bumped the version to 0.4.0 for these changes.
